export const data={
 ls:'la-storage-ng',
 time:1500,
 stepViews:[],
 view:{
  el:'.overlay-block',
  shownCls:'shown',
  noBgCls:'no-bg',
  noAnimCls:'no-anim',
  isLearnCls:'isLearn'
 },
 ach:{
  el:'.achievement-pop',
  template:'#achievement-template'
 },
 art:{
  el:'.article-pop',
  template:'#article-template'
 }
};