export const data={
 template:'',
 src:{
  'action':{src:'action',loop:true},
  'trevoga':{src:'trevoga',loop:true},
  'huliganskaya':{src:'huliganskaya',loop:true},
  'liric':{src:'liric',loop:true},
  'btn':{src:'click',loop:false},
  'btn-h':{src:'hover',loop:false},
  'yes':{src:'yes',loop:false},
  'no':{src:'no',loop:false},
  'pulse':{src:'pulse',loop:false},
  'voice0':{src:'voice0',loop:false},
  'voice1':{src:'voice1',loop:false},
  'voice11':{src:'voice11',loop:false},
  'voice12':{src:'voice12',loop:false},
  'voice3':{src:'voice3',loop:false},
  'voice5':{src:'voice5',loop:false},
  'voice6':{src:'voice6',loop:false},
  'voice7':{src:'voice7',loop:false},
  'voice8':{src:'voice8',loop:false}
 }
};